apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
#        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
#          value: foo
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
          valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: paulczar/spring-hello
        imagePullPolicy: Always
        name: hello
        resources: {}
