apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring
subjects:
- kind: ServiceAccount
  name: default
